import React, { useState, useEffect } from "react";
import {
  Text,
  StyleSheet,
  SafeAreaView,
  View,
  Image,
  StatusBar,
  TouchableOpacity,
  Keyboard,
  KeyboardAvoidingView,
  ScrollView,
  TextInput,
} from "react-native";

import MyGarden from "../1_MainScreens/3_MyGarden";
import QuickView from "./QuickView.js";
// import PlantPortrait from "./PlantPortrait";
import Diary from "./Diary";
import Task from "../../components/Task";
import StylePlants from "../../styles/StylePlants";

// for styling
import { Colors } from "react-native/Libraries/NewAppScreen";
import colors from "../../config/colors";

const DetailedPLantBanderole = () => {
  return (
    <View style={[StylePlants.banderole]}>
      {/* --------------------------------------------------------------- Banderole */}
      {/* <SafeAreaView style={StylePlants.banderole}>
  <Text style={StylePlants.mainText}>Pflanzenportrait</Text>
</SafeAreaView>; */}
      <Text style={detailedPlantPortraitStyles.plantTitle}>
        Name Pflanzensorte
      </Text>
      <Text style={detailedPlantPortraitStyles.plantVarietyName}>
        "Sortenname spezifisch"
      </Text>
      <Text style={detailedPlantPortraitStyles.botanicalName}>
        botanischer Name
      </Text>
      <View
        name="plant_time_container"
        style={detailedPlantPortraitStyles.banderoleArea}
      >
        <View
          name="plant_time_titles_container"
          style={detailedPlantPortraitStyles.banderoleArea}
        >
          <View
            name="plant_time_title"
            style={detailedPlantPortraitStyles.banderoleArea}
          ></View>
          <View
            name="plant_time_title"
            style={detailedPlantPortraitStyles.banderoleArea}
          ></View>
          <View
            name="plant_time_title"
            style={detailedPlantPortraitStyles.banderoleArea}
          ></View>
        </View>
        <View
          name="plant_time_months_outer_container"
          style={detailedPlantPortraitStyles.monthsOuterContainer}
        >
          <View
            name="plant_time_months_inner_container"
            style={detailedPlantPortraitStyles.monthsInnerContainer}
          >
            <View
              name="plant_time_month"
              style={[
                detailedPlantPortraitStyles.border,
                detailedPlantPortraitStyles.monthBox,
              ]}
            >
              <Text
                name="month_name"
                style={[
                  detailedPlantPortraitStyles.border,
                  detailedPlantPortraitStyles.monthName,
                ]}
              >
                Jan
              </Text>
              <View
                name="plant_time_month"
                style={[
                  detailedPlantPortraitStyles.border,
                  detailedPlantPortraitStyles.monthBox,
                ]}
              >
                <Text
                  name="month_name"
                  style={[
                    detailedPlantPortraitStyles.border,
                    detailedPlantPortraitStyles.monthName,
                  ]}
                >
                  Jan
                </Text>
              </View>
              <View
                name="plant_time_month"
                style={[
                  detailedPlantPortraitStyles.border,
                  detailedPlantPortraitStyles.monthBox,
                ]}
              >
                <Text
                  name="month_name"
                  style={[
                    detailedPlantPortraitStyles.border,
                    detailedPlantPortraitStyles.monthName,
                  ]}
                >
                  Jan
                </Text>
              </View>
              <View
                name="plant_time_month"
                style={[
                  detailedPlantPortraitStyles.border,
                  detailedPlantPortraitStyles.monthBox,
                ]}
              >
                <Text
                  name="month_name"
                  style={[
                    detailedPlantPortraitStyles.border,
                    detailedPlantPortraitStyles.monthName,
                  ]}
                >
                  Jan
                </Text>
              </View>
              <View
                name="plant_time_month"
                style={[
                  detailedPlantPortraitStyles.border,
                  detailedPlantPortraitStyles.monthBox,
                ]}
              >
                <Text
                  name="month_name"
                  style={[
                    detailedPlantPortraitStyles.border,
                    detailedPlantPortraitStyles.monthName,
                  ]}
                >
                  Jan
                </Text>
              </View>
              <View
                name="plant_time_month"
                style={[
                  detailedPlantPortraitStyles.border,
                  detailedPlantPortraitStyles.monthBox,
                ]}
              >
                <Text
                  name="month_name"
                  style={[
                    detailedPlantPortraitStyles.border,
                    detailedPlantPortraitStyles.monthName,
                  ]}
                >
                  Jan
                </Text>
              </View>
              <View
                name="plant_time_month"
                style={[
                  detailedPlantPortraitStyles.border,
                  detailedPlantPortraitStyles.monthBox,
                ]}
              >
                <Text
                  name="month_name"
                  style={[
                    detailedPlantPortraitStyles.border,
                    detailedPlantPortraitStyles.monthName,
                  ]}
                >
                  Jan
                </Text>
              </View>
              <View
                name="plant_time_month"
                style={[
                  detailedPlantPortraitStyles.border,
                  detailedPlantPortraitStyles.monthBox,
                ]}
              >
                <Text
                  name="month_name"
                  style={[
                    detailedPlantPortraitStyles.border,
                    detailedPlantPortraitStyles.monthName,
                  ]}
                >
                  Jan
                </Text>
              </View>
              <View
                name="plant_time_month"
                style={[
                  detailedPlantPortraitStyles.border,
                  detailedPlantPortraitStyles.monthBox,
                ]}
              >
                <Text
                  name="month_name"
                  style={[
                    detailedPlantPortraitStyles.border,
                    detailedPlantPortraitStyles.monthName,
                  ]}
                >
                  Jan
                </Text>
              </View>
              <View
                name="plant_time_month"
                style={[
                  detailedPlantPortraitStyles.border,
                  detailedPlantPortraitStyles.monthBox,
                ]}
              >
                <Text
                  name="month_name"
                  style={[
                    detailedPlantPortraitStyles.border,
                    detailedPlantPortraitStyles.monthName,
                  ]}
                >
                  Jan
                </Text>
              </View>
              <View
                name="plant_time_month"
                style={[
                  detailedPlantPortraitStyles.border,
                  detailedPlantPortraitStyles.monthBox,
                ]}
              >
                <Text
                  name="month_name"
                  style={[
                    detailedPlantPortraitStyles.border,
                    detailedPlantPortraitStyles.monthName,
                  ]}
                >
                  Jan
                </Text>
              </View>
              <View
                name="plant_time_month"
                style={[
                  detailedPlantPortraitStyles.border,
                  detailedPlantPortraitStyles.monthBox,
                ]}
              >
                <Text
                  name="month_name"
                  style={[
                    detailedPlantPortraitStyles.border,
                    detailedPlantPortraitStyles.monthName,
                  ]}
                >
                  Dez
                </Text>
              </View>
            </View>
          </View>
          <View
            name="plant_time_months_inner_container"
            style={detailedPlantPortraitStyles.monthsInnerContainer}
          >
            <View
              name="plant_time_month"
              style={[
                detailedPlantPortraitStyles.border,
                detailedPlantPortraitStyles.monthBox,
              ]}
            ></View>
            <View
              name="plant_time_month"
              style={[
                detailedPlantPortraitStyles.border,
                detailedPlantPortraitStyles.monthBox,
              ]}
            ></View>
            <View
              name="plant_time_month"
              style={[
                detailedPlantPortraitStyles.border,
                detailedPlantPortraitStyles.monthBox,
              ]}
            ></View>
            <View
              name="plant_time_month"
              style={[
                detailedPlantPortraitStyles.border,
                detailedPlantPortraitStyles.monthBox,
              ]}
            ></View>
            <View
              name="plant_time_month"
              style={[
                detailedPlantPortraitStyles.border,
                detailedPlantPortraitStyles.monthBox,
              ]}
            ></View>
            <View
              name="plant_time_month"
              style={[
                detailedPlantPortraitStyles.border,
                detailedPlantPortraitStyles.monthBox,
              ]}
            ></View>
            <View
              name="plant_time_month"
              style={[
                detailedPlantPortraitStyles.border,
                detailedPlantPortraitStyles.monthBox,
              ]}
            ></View>
            <View
              name="plant_time_month"
              style={[
                detailedPlantPortraitStyles.border,
                detailedPlantPortraitStyles.monthBox,
              ]}
            ></View>
            <View
              name="plant_time_month"
              style={[
                detailedPlantPortraitStyles.border,
                detailedPlantPortraitStyles.monthBox,
              ]}
            ></View>
            <View
              name="plant_time_month"
              style={[
                detailedPlantPortraitStyles.border,
                detailedPlantPortraitStyles.monthBox,
              ]}
            ></View>
            <View
              name="plant_time_month"
              style={[
                detailedPlantPortraitStyles.border,
                detailedPlantPortraitStyles.monthBox,
              ]}
            ></View>
            <View
              name="plant_time_month"
              style={[
                detailedPlantPortraitStyles.border,
                detailedPlantPortraitStyles.monthBox,
              ]}
            ></View>
          </View>
          <View
            name="plant_time_months_inner_container"
            style={detailedPlantPortraitStyles.monthsInnerContainer}
          >
            <View
              name="plant_time_month"
              style={[
                detailedPlantPortraitStyles.border,
                detailedPlantPortraitStyles.monthBox,
              ]}
            ></View>
            <View
              name="plant_time_month"
              style={[
                detailedPlantPortraitStyles.border,
                detailedPlantPortraitStyles.monthBox,
              ]}
            ></View>
            <View
              name="plant_time_month"
              style={[
                detailedPlantPortraitStyles.border,
                detailedPlantPortraitStyles.monthBox,
              ]}
            ></View>
            <View
              name="plant_time_month"
              style={[
                detailedPlantPortraitStyles.border,
                detailedPlantPortraitStyles.monthBox,
              ]}
            ></View>
            <View
              name="plant_time_month"
              style={[
                detailedPlantPortraitStyles.border,
                detailedPlantPortraitStyles.monthBox,
              ]}
            ></View>
            <View
              name="plant_time_month"
              style={[
                detailedPlantPortraitStyles.border,
                detailedPlantPortraitStyles.monthBox,
              ]}
            ></View>
            <View
              name="plant_time_month"
              style={[
                detailedPlantPortraitStyles.border,
                detailedPlantPortraitStyles.monthBox,
              ]}
            ></View>
            <View
              name="plant_time_month"
              style={[
                detailedPlantPortraitStyles.border,
                detailedPlantPortraitStyles.monthBox,
              ]}
            ></View>
            <View
              name="plant_time_month"
              style={[
                detailedPlantPortraitStyles.border,
                detailedPlantPortraitStyles.monthBox,
              ]}
            ></View>
            <View
              name="plant_time_month"
              style={[
                detailedPlantPortraitStyles.border,
                detailedPlantPortraitStyles.monthBox,
              ]}
            ></View>
            <View
              name="plant_time_month"
              style={[
                detailedPlantPortraitStyles.border,
                detailedPlantPortraitStyles.monthBox,
              ]}
            ></View>
            <View
              name="plant_time_month"
              style={[
                detailedPlantPortraitStyles.border,
                detailedPlantPortraitStyles.monthBox,
              ]}
            ></View>
          </View>
        </View>
      </View>
    </View>
  );
};

const styles = StyleSheet.create({
  // platformContainer: {
  //   flex: 1,
  //   paddingTop: Platform.OS === "android" ? StatusBar.currentHeight : 0,
  // },
});
export default DetailedPLantBanderole;
